services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - HOST_URL=192.168.1.200
    restart: unless-stopped
